// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rozrghqlfhyjcwqqjfbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvenJnaHFsZmh5amN3cXFqZmJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTMyMDEsImV4cCI6MjA2NDY2OTIwMX0.XxvuX0AXND0MudfvamCud8_WlMyOxVMdra58gTL6u_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);